const assert=require('node:assert/strict');const path=require('node:path');const H=require(path.join(__dirname,'../ui/hexabble/engine.js'));
let n=0;function test(name,fn){fn();n++;console.log('PASS '+name)}
const letters=(s,coords)=>s.split('').map((letter,i)=>({q:coords[i][0],r:coords[i][1],tile:{id:'fixture-'+i,kind:'letter',letter,value:H.LETTERS[letter][1]}}));const dict=new Set(['cat','aa','at','ate','cats','a']);
test('217 unique bounded cells and six key spaces',()=>{assert.equal(H.allCells().length,217);assert.equal(new Set(H.allCells().map(c=>H.key(...c))).size,217);assert.equal(H.KEY_LOCATIONS.length,6)});
test('108 unique tiles and seven-tile rack',()=>{assert.equal(H.makeTiles().length,108);assert.equal(new Set(H.makeTiles().map(t=>t.id)).size,108);let g=H.createGame(['A','B'],{mode:'friendly'},()=>.5);assert.equal(g.players[0].rack.length,7);assert.equal(g.bag.length,94)});
test('CAT at centre scores10',()=>{let a=H.analyzeMove({},letters('CAT',[[0,0],[0,1],[0,2]]),dict);assert.equal(a.ok,true);assert.equal(a.score,10)});
test('Opening must cover centre',()=>assert(H.analyzeMove({},letters('CAT',[[1,0],[1,1],[1,2]]),dict).placementError));
test('Gapped opening rejected',()=>assert(H.analyzeMove({},letters('CAT',[[0,0],[0,1],[0,3]]),dict).placementError));
test('Occupied cell rejected',()=>{const t=H.makeTiles().find(x=>x.letter==='A');let b={'0,0':{tile:t,letter:'A',value:1}};assert(H.analyzeMove(b,letters('AT',[[0,0],[0,1]]),dict).placementError)});
test('Wild letter zero value while centre doubles word',()=>{let p=letters('CAT',[[0,0],[0,1],[0,2]]);p[0].tile={id:'w',kind:'wild',letter:null,value:0};p[0].assigned='C';let a=H.analyzeMove({},p,dict);assert(a.ok);assert.equal(a.score,4)});
function moveGame(mode,word){const g=H.createGame(['A','B'],{mode},()=>.5);const pool=[...g.bag,...g.players.flatMap(p=>p.rack)],used=[];for(const l of word){const t=pool.find(t=>t.letter===l&&!used.some(u=>u.id===t.id));used.push(t)}const ids=new Set(used.map(t=>t.id));for(const p of g.players)p.rack=p.rack.filter(t=>!ids.has(t.id));g.bag=pool.filter(t=>!ids.has(t.id)&&!g.players.some(p=>p.rack.some(u=>u.id===t.id)));g.players[0].rack=used;return{g,placements:used.map((t,i)=>({q:0,r:i,tileId:t.id}))}}
test('Friendly invalid word does not mutate turn/rack/board',()=>{let{g,placements}=moveGame('friendly','AT');let before=JSON.stringify(g);assert.equal(H.playMove(g,placements,new Set()).status,'error');assert.equal(JSON.stringify(g),before)});
test('Challenge invalid word loses turn but keeps rack and board',()=>{let{g,placements}=moveGame('official','AT');let rack=g.players[0].rack.map(t=>t.id);assert.equal(H.playMove(g,placements,new Set()).status,'challenged');assert.equal(g.current,1);assert.deepEqual(g.players[0].rack.map(t=>t.id),rack);assert.equal(Object.keys(g.board).length,0)});
test('Duplicate rack tile IDs rejected atomically',()=>{let{g}=moveGame('friendly','AA');const id=g.players[0].rack[0].id,before=JSON.stringify(g);assert.equal(H.playMove(g,[{q:0,r:0,tileId:id},{q:0,r:1,tileId:id}],dict).status,'error');assert.equal(JSON.stringify(g),before)});
test('Fractional coordinate and multi-character assignment rejected',()=>{let{g,placements}=moveGame('friendly','AT');assert.equal(H.playMove(g,[{...placements[0],q:.5}],dict).status,'error');assert.equal(H.playMove(g,[{...placements[0],assigned:'AA'}],dict).status,'error')});
test('Exchange rejects below7bag without mutating',()=>{let g=H.createGame(['A','B'],{},()=>.5);g.bag=g.bag.slice(0,6);let before=JSON.stringify(g);assert.equal(H.exchange(g,[g.players[0].rack[0].id]).status,'error');assert.equal(JSON.stringify(g),before)});
test('Four consecutive passes end two-player game',()=>{let g=H.createGame(['A','B'],{},()=>.5);for(let i=0;i<4;i++)H.pass(g);assert(g.over);assert.equal(g.turn,4);assert(g.winners.length>=1)});
test('Manual end is idempotent and deducts unplayed tiles',()=>{let g=H.createGame(['A','B'],{},()=>.5);let values=g.players.map(H.rackValue);H.endGame(g,null,'Test');assert.deepEqual(g.players.map(p=>p.score),values.map(v=>-v));let before=JSON.stringify(g);H.endGame(g,null,'Again');assert.equal(JSON.stringify(g),before)});
test('Malformed placement records are rejected',()=>{let g=H.createGame(['A','B'],{},()=>.5);assert.equal(H.playMove(g,[null],dict).status,'error');assert.equal(H.playMove(g,[{}],dict).status,'error')});
const fixtures=require(path.join(__dirname,'../content/hexabble.json'));
for(const round of fixtures.rounds)test(round.id+' expected scoring',()=>{const a=H.analyzeMove(round.board,round.placements,new Set(round.acceptedWords));assert.equal(a.ok,round.expected.valid);assert.equal(a.score,round.expected.score)});
console.log(n+' engine checks passed. This subset does not prove all pivot/adjacency/premium cases.');
