/* Writes docs/STATUS.md: per-game readiness derived from the registry (never hand-edited). */
import { writeFileSync } from "node:fs";
import { GAMES, getRounds } from "../../src/games/registry";

const lines: string[] = [
  "# Word Club status",
  "",
  "Generated by `pnpm status` from the game registry. Do not edit by hand.",
  "",
  "| Game | Availability | Production enabled | Gentle | Standard | Expert | Master | Demo fixtures | Open gates |",
  "|---|---|---|---:|---:|---:|---:|---:|---|",
];
for (const g of GAMES) {
  const r = getRounds(g.id);
  const by = (d: string) => r.filter((x) => x.meta.difficulty === d).length;
  const open = g.releaseGates.filter((x) => x.status === "open").map((x) => x.gate);
  lines.push(
    `| ${g.title} | ${g.availability} | ${g.productionEnabled ? "yes" : "no"} | ${by("gentle")} | ${by("standard")} | ${by("expert")} | ${by("master")} | ${r.filter((x) => x.meta.status === "demo").length} | ${open.length} |`,
  );
}
lines.push("", "## Release gates per game", "");
for (const g of GAMES) {
  lines.push(`### ${g.title}`, "");
  for (const gate of g.releaseGates) lines.push(`- ${gate.status === "passed" ? "[x]" : gate.status === "open" ? "[ ]" : "[-]"} ${gate.gate}${gate.note ? ` (${gate.note})` : ""}`);
  lines.push("");
}
writeFileSync("docs/STATUS.md", lines.join("\n"));
console.log("Wrote docs/STATUS.md");
