/**
 * Hexabble board geometry, migrated without semantic change from the adapted reference
 * engine (reference/build-pack-v3/ui/hexabble/engine.js).
 *
 * Flat-topped hexes in axial coordinates (q = column, r). The board is a radius-8 hexagon:
 * 217 cells, 17 cells across. Words read along three directions only.
 */

export const RADIUS = 8;

export type Vec = readonly [number, number];

/** Reading directions, in the source order (the order matters for tie-breaking). */
export const DIRS: readonly Vec[] = [
  [0, 1],
  [1, 0],
  [1, -1],
];
export const DIR_NAMES = ["down", "down-right", "up-right"] as const;
export type DirName = (typeof DIR_NAMES)[number];
export const DIR_ARROWS: Record<DirName, string> = { down: "↓", "down-right": "↘", "up-right": "↗" };

/** All six neighbours of a cell. */
export const NEIGHBOURS: readonly Vec[] = [
  [0, 1],
  [1, 0],
  [1, -1],
  [0, -1],
  [-1, 0],
  [-1, 1],
];

export type CellKey = string;
export const cellKey = (q: number, r: number): CellKey => `${q + 0},${r + 0}`;

export function inBoard(q: number, r: number): boolean {
  return (
    Number.isInteger(q) &&
    Number.isInteger(r) &&
    Math.abs(q) <= RADIUS &&
    Math.abs(r) <= RADIUS &&
    Math.abs(q + r) <= RADIUS
  );
}

/** Strictly parse "q,r" into integer in-board coordinates, or null. */
export function parseCellKey(key: unknown): [number, number] | null {
  if (typeof key !== "string" || !/^-?\d{1,2},-?\d{1,2}$/.test(key)) return null;
  const [q, r] = key.split(",").map(Number);
  if (!inBoard(q, r)) return null;
  if (cellKey(q, r) !== key) return null; // rejects "-0,1" and "01,2"
  return [q, r];
}

export type Premium = "DL" | "TL" | "DW" | "TW" | "KEY" | "START";

/** All distinct axial cells generated by permuting a cube coordinate and its negation. */
function cubePerms(x: number, y: number, z: number): [number, number][] {
  const out = new Map<string, [number, number]>();
  const base: [number, number, number][] = [
    [x, y, z],
    [-x, -y, -z],
  ];
  for (const [a, b, c] of base) {
    const pairs: [number, number][] = [
      [a, b],
      [a, c],
      [b, a],
      [b, c],
      [c, a],
      [c, b],
    ];
    for (const [p, s] of pairs) out.set(cellKey(p, s), [p + 0, s + 0]);
  }
  return [...out.values()];
}

const PREMIUM: Record<string, Premium> = {};
const setP = (list: [number, number][], t: Premium) => list.forEach(([q, r]) => (PREMIUM[cellKey(q, r)] = t));
setP(cubePerms(8, 0, -8), "TW");
setP(cubePerms(4, 4, -8), "TL");
setP(cubePerms(1, 6, -7), "DW");
setP(cubePerms(3, 3, -6), "KEY");
setP(cubePerms(1, 4, -5), "DL");
setP(cubePerms(2, 2, -4), "DL");
setP(cubePerms(1, 1, -2), "DL");
PREMIUM[cellKey(0, 0)] = "START";

/** The six Key spaces. */
export const KEY_LOCATIONS: readonly (readonly [number, number])[] = cubePerms(3, 3, -6);

export const premiumAt = (q: number, r: number): Premium | null => PREMIUM[cellKey(q, r)] ?? null;

export const LETTER_MULT: Partial<Record<Premium, number>> = { DL: 2, TL: 3 };
/** Word multipliers. Several on one word ADD (DW + TW = 5x), they do not multiply. */
export const WORD_MULT: Partial<Record<Premium, number>> = { DW: 2, KEY: 2, START: 2, TW: 3 };

export const PREMIUM_LABEL: Record<Premium, string> = {
  DL: "double letter",
  TL: "triple letter",
  DW: "double word",
  TW: "triple word",
  KEY: "Key space, double word",
  START: "centre start, double word",
};

let cellsMemo: [number, number][] | null = null;
/** Every legal cell, column by column (q ascending, then r ascending), as in the source. */
export function allCells(): [number, number][] {
  if (!cellsMemo) {
    const cells: [number, number][] = [];
    for (let q = -RADIUS; q <= RADIUS; q++) for (let r = -RADIUS; r <= RADIUS; r++) if (inBoard(q, r)) cells.push([q, r]);
    cellsMemo = cells;
  }
  return cellsMemo.map(([q, r]) => [q, r]);
}
