/**
 * Pure word-graph helpers for Word Ladder. Two words are adjacent when they have the same
 * length and differ by exactly one substituted letter. The graph is implicit: neighbours are
 * generated by trying every substitution against a membership set.
 */
const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

export function hamming(a: string, b: string): number {
  if (a.length !== b.length) return Infinity;
  let n = 0;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) n++;
  return n;
}

export function neighbours(word: string, has: (w: string) => boolean): string[] {
  const out: string[] = [];
  for (let i = 0; i < word.length; i++) {
    for (const c of ALPHABET) {
      if (c === word[i]) continue;
      const w = word.slice(0, i) + c + word.slice(i + 1);
      if (has(w)) out.push(w);
    }
  }
  return out;
}

/** Breadth-first distances from `from` to every reachable word. */
export function distancesFrom(from: string, has: (w: string) => boolean): Map<string, number> {
  const dist = new Map<string, number>([[from, 0]]);
  const queue = [from];
  for (let i = 0; i < queue.length; i++) {
    const cur = queue[i];
    const d = dist.get(cur)!;
    for (const n of neighbours(cur, has)) {
      if (!dist.has(n)) {
        dist.set(n, d + 1);
        queue.push(n);
      }
    }
  }
  return dist;
}

/** One shortest path from a to b (alphabetically first at each step), or null. */
export function shortestPath(a: string, b: string, has: (w: string) => boolean): string[] | null {
  const dist = distancesFrom(b, has);
  if (!dist.has(a)) return null;
  const path = [a];
  while (path[path.length - 1] !== b) {
    const cur = path[path.length - 1];
    const d = dist.get(cur)!;
    const next = neighbours(cur, has)
      .filter((n) => dist.get(n) === d - 1)
      .sort()[0];
    path.push(next);
  }
  return path;
}

/** True when every consecutive pair differs by exactly one letter. */
export function isLadder(path: readonly string[]): boolean {
  return path.every((w, i) => i === 0 || hamming(path[i - 1], w) === 1);
}
