/** Small pure text helpers and the house abbreviation table shared by the clue checkers. */

/**
 * Allowed abbreviations (source phrase, lower case) -> letters. House list: only conventional
 * crossword short forms belong here (a cryptic solver would expect each without explanation).
 * Anything arguable is a "synonym" part instead, which is listed for human review.
 */
export const ABBREVIATIONS: Record<string, readonly string[]> = {
  thanks: ["TA"],
  ring: ["O"],
  energy: ["E"],
  time: ["T"],
  quiet: ["P"],
  about: ["C", "CA", "RE"],
  ace: ["A"],
  afternoon: ["PM"],
  american: ["A", "AM"],
  answer: ["A", "ANS"],
  artist: ["RA"],
  bachelor: ["B", "BA"],
  bishop: ["B", "RR"],
  black: ["B"],
  born: ["B", "NEE"],
  bowled: ["B"],
  boy: ["B"],
  brother: ["BR"],
  carbon: ["C"],
  castle: ["R"],
  catholic: ["RC"],
  caught: ["C"],
  cent: ["C"],
  chapter: ["C", "CH"],
  church: ["CE", "CH"],
  circle: ["O"],
  clubs: ["C"],
  cold: ["C"],
  colonel: ["COL"],
  conservative: ["C", "CON"],
  copper: ["CU", "P", "D"],
  cross: ["X"],
  daughter: ["D"],
  day: ["D"],
  degree: ["BA", "MA", "BSC"],
  diamonds: ["D"],
  died: ["D"],
  direction: ["N", "E", "S", "W"],
  doctor: ["DR", "MO", "MB", "GP", "DOC"],
  duck: ["O"],
  east: ["E"],
  editor: ["ED"],
  egg: ["O"],
  engineers: ["RE"],
  european: ["E"],
  female: ["F"],
  fine: ["F"],
  following: ["F"],
  foot: ["FT"],
  force: ["F"],
  forte: ["F"],
  french: ["F"],
  friar: ["FR"],
  general: ["GEN"],
  girl: ["G"],
  gold: ["OR", "AU"],
  good: ["G", "PI"],
  graduate: ["BA", "MA"],
  grand: ["G", "K"],
  gram: ["G"],
  gunners: ["RA"],
  hard: ["H"],
  hearts: ["H"],
  heroin: ["H"],
  horse: ["H"],
  hospital: ["H"],
  hot: ["H"],
  hour: ["H", "HR"],
  husband: ["H"],
  iron: ["FE"],
  island: ["I", "IS"],
  italian: ["IT"],
  jack: ["J"],
  journalist: ["ED"],
  judge: ["J"],
  king: ["K", "R", "REX"],
  kiss: ["X"],
  knight: ["K", "N", "KT"],
  lake: ["L"],
  large: ["L"],
  lead: ["PB"],
  learner: ["L"],
  left: ["L"],
  liberal: ["L"],
  line: ["L"],
  lines: ["LL"],
  lieutenant: ["LT"],
  litre: ["L"],
  loud: ["F"],
  loudly: ["F"],
  love: ["O"],
  maiden: ["M"],
  male: ["M"],
  major: ["MAJ"],
  married: ["M"],
  master: ["M"],
  member: ["M", "MP"],
  metre: ["M"],
  mile: ["M"],
  minute: ["M", "MIN"],
  morning: ["AM"],
  navy: ["RN"],
  new: ["N"],
  nitrogen: ["N"],
  no: ["N"],
  noon: ["N"],
  north: ["N"],
  nothing: ["O", "NIL"],
  number: ["N", "NO"],
  ounce: ["OZ"],
  ounces: ["OZ"],
  officer: ["OC", "CO", "COL", "MAJ", "LT"],
  old: ["O", "EX"],
  one: ["I", "A", "AN", "UN"],
  over: ["O"],
  oxygen: ["O"],
  page: ["P"],
  pages: ["PP"],
  pawn: ["P"],
  pence: ["P"],
  penny: ["P", "D"],
  piano: ["P"],
  point: ["N", "E", "S", "W", "PT"],
  politician: ["MP"],
  pound: ["L", "LB"],
  president: ["P"],
  pressure: ["P"],
  priest: ["FR"],
  queen: ["Q", "R", "ER"],
  question: ["Q"],
  quarter: ["N", "E", "S", "W"],
  right: ["R"],
  river: ["R"],
  road: ["RD", "ST", "AVE"],
  rook: ["R"],
  run: ["R"],
  runs: ["R"],
  sailor: ["AB"],
  saint: ["S", "ST"],
  scholar: ["BA", "MA"],
  second: ["S"],
  sergeant: ["SGT"],
  shilling: ["S"],
  sister: ["SR"],
  small: ["S"],
  soft: ["P"],
  softly: ["P"],
  soldiers: ["RE", "OR", "TA"],
  son: ["S"],
  south: ["S"],
  spades: ["S"],
  street: ["ST"],
  succeeded: ["S"],
  ten: ["X"],
  thousand: ["K", "M"],
  times: ["X"],
  ton: ["T", "C"],
  tungsten: ["W"],
  turn: ["U"],
  unknown: ["X", "Y", "Z"],
  university: ["U"],
  uranium: ["U"],
  very: ["V"],
  victory: ["V"],
  versus: ["V"],
  volume: ["V", "VOL"],
  vote: ["X"],
  weight: ["W", "WT"],
  week: ["W", "WK"],
  west: ["W"],
  width: ["W"],
  wicket: ["W"],
  wife: ["W"],
  with: ["W"],
  without: ["WO"],
  women: ["W"],
  year: ["Y", "YR"],
  yard: ["Y", "YD"],
  zero: ["O"],
  "extra large": ["XL"],
  "for example": ["EG"],
  "that is": ["IE"],
  "very loud": ["FF"],
  "very quiet": ["PP"],
  "upper class": ["U"],
  "commanding officer": ["CO"],
  "european union": ["EU"],
  "bridge player": ["N", "E", "S", "W"],
  "hospital department": ["ENT"],
  "the french": ["LE", "LA", "LES"],
  "the spanish": ["EL", "LA", "LOS"],
  "the german": ["DER", "DIE", "DAS"],
  "a french": ["UN", "UNE"],
  "of french": ["DE"],
  "in french": ["EN", "DANS"],
};

export const normaliseLetters = (s: string) =>
  s
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toUpperCase()
    .replace(/[^A-Z]/g, "");

export const sortLetters = (s: string) => [...s].sort().join("");
export const reverse = (s: string) => [...s].reverse().join("");

export interface Span {
  start: number;
  end: number;
}

/**
 * Every whole-word, case-insensitive occurrence of `phrase` in `text`.
 * "in" does not match inside "interior".
 */
export function findPhrase(text: string, phrase: string): Span[] {
  const out: Span[] = [];
  if (!phrase.trim()) return out;
  const hay = text.toLowerCase();
  const needle = phrase.toLowerCase();
  let from = 0;
  for (;;) {
    const i = hay.indexOf(needle, from);
    if (i < 0) break;
    const before = i === 0 ? "" : hay[i - 1];
    const after = hay[i + needle.length] ?? "";
    if (!/[a-z]/.test(before) && !/[a-z]/.test(after)) out.push({ start: i, end: i + needle.length });
    from = i + 1;
  }
  return out;
}
