/* Authoring helper (not imported by the app): builds content/rounds.json from a compact table, sets
 * claimsUnique only when the solver proves it, and prints rival boards for editorial review.
 * Run: pnpm exec tsx src/games/word-fragments/author.gen.ts */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { createRng, seedFrom } from "@/lib/rng";
import { loadMembershipSync } from "@/lib/dictionary/node";
import type { FragPayload } from "./engine";
import { acceptedTextAllocations, rivalBoards } from "./validate-core";

type Row = {
  id: string;
  title: string;
  difficulty: "gentle" | "standard" | "expert" | "master";
  status: "demo" | "practice";
  source: string | null;
  /** [clue, "FRAG|MENT|S"] per lane */
  lanes: [string, string][];
  explanation: string;
  /** Keep the pack's tile ids/order for demo fixtures. */
  keepOrder?: boolean;
};

const rows: Row[] = [
  { id: "wf-demo-1", title: "Original demo board 1", difficulty: "gentle", status: "demo", source: "fragments-001", keepOrder: true, lanes: [["Paper money represented by a single note", "BANK|NOTE"], ["An arc of colours seen when sunlight passes through rain", "RAIN|BOW"], ["A tall plant with a large yellow flower head", "SUN|FLOW|ER"]], explanation: "Every fragment is consumed exactly once." },
  { id: "wf-demo-2", title: "Original demo board 2", difficulty: "gentle", status: "demo", source: "fragments-002", keepOrder: true, lanes: [["A marker placed between pages to keep your place", "BOOK|MARK"], ["An insect with broad, often colourful wings", "BUT|TER|FLY"], ["The hard outer covering of a marine mollusc", "SEA|SHELL"]], explanation: "The target spellings use all seven fragment tiles." },
  { id: "wf-g1", title: "Gentle board 1", difficulty: "gentle", status: "practice", source: null, lanes: [["Bright light from the sun", "SUN|SHINE"], ["A pot with a spout for brewing a hot drink", "TEA|POT"], ["A game played by two teams of eleven, kicking a ball", "FOOT|BALL"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-g2", title: "Gentle board 2", difficulty: "gentle", status: "practice", source: null, lanes: [["A cabinet with shelves, often in a kitchen", "CUP|BOARD"], ["A waterproof coat", "RAIN|COAT"], ["The step just outside a front door", "DOOR|STEP"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-g3", title: "Gentle board 3", difficulty: "gentle", status: "practice", source: null, lanes: [["A ball of packed snow for throwing", "SNOW|BALL"], ["A trim at the barber's or hairdresser's", "HAIR|CUT"], ["A thin flat cake fried in a pan, eaten on Shrove Tuesday", "PAN|CAKE"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-g4", title: "Gentle board 4", difficulty: "gentle", status: "practice", source: null, lanes: [["The room where you sleep", "BED|ROOM"], ["A tower with a bright lamp that guides ships", "LIGHT|HOUSE"], ["A sea creature shaped like a five-pointed star", "STAR|FISH"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-g5", title: "Gentle board 5", difficulty: "gentle", status: "practice", source: null, lanes: [["The anniversary of the day you were born", "BIRTH|DAY"], ["A stream of water dropping over a cliff", "WATER|FALL"], ["A small bag for carrying a purse and keys", "HAND|BAG"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-s1", title: "Standard board 1", difficulty: "standard", status: "practice", source: null, lanes: [["A plot of land where flowers and vegetables grow", "GAR|DEN"], ["A thick floor covering", "CAR|PET"], ["A container woven from cane or wicker", "BAS|KET"]], explanation: "Each word splits into two spelling chunks, and the first chunks look interchangeable: only one sharing-out spells all three answers." },
  { id: "wf-s2", title: "Standard board 2", difficulty: "standard", status: "practice", source: null, lanes: [["A room where food is cooked", "KIT|CHEN"], ["A farmyard bird that lays eggs", "CHIC|KEN"], ["A glove without separate finger sections", "MIT|TEN"]], explanation: "KIT and MIT, CHEN, KEN and TEN look as if they could swap; the clues decide." },
  { id: "wf-s3", title: "Standard board 3", difficulty: "standard", status: "practice", source: null, lanes: [["A seafarer who robs ships", "PI|RATE"], ["A round citrus fruit", "OR|ANGE"], ["A world that travels round a star", "PLAN|ET"], ["A pale yellow spread made from cream", "BUT|TER"]], explanation: "Four lanes, with chunks split inside the words rather than at syllables." },
  { id: "wf-s4", title: "Standard board 4", difficulty: "standard", status: "practice", source: null, lanes: [["A writing tool with a graphite core", "PEN|CIL"], ["An opening in a wall that lets in light", "WIN|DOW"], ["A meal eaten outdoors", "PIC|NIC"]], explanation: "Spelling chunks, not syllables: PEN+CIL, WIN+DOW, PIC+NIC." },
  { id: "wf-s5", title: "Standard board 5", difficulty: "standard", status: "practice", source: null, lanes: [["A tool for knocking in nails", "HAM|MER"], ["A stick of wax with a wick", "CAN|DLE"], ["A flat piece of furniture with legs", "TA|BLE"], ["A large black and white bear from China", "PAN|DA"]], explanation: "CAN and PAN, TA and DA look as if they could swap; only one sharing-out spells all four answers." },
  { id: "wf-e1", title: "Expert board 1", difficulty: "expert", status: "practice", source: null, lanes: [["A long-tailed animal that climbs trees", "MON|KEY"], ["A long-eared animal related to the horse", "DON|KEY"], ["A large bird often roasted at Christmas", "TUR|KEY"], ["A team game played with sticks, on a field or on ice", "HOC|KEY"]], explanation: "Four identical KEY tiles: any KEY can finish any lane, so the challenge is pairing the openings." },
  { id: "wf-e2", title: "Expert board 2", difficulty: "expert", status: "practice", source: null, lanes: [["A starchy vegetable dug from the ground", "POT|ATO"], ["A red fruit used in salads and sauces", "TOM|ATO"], ["The lowest part of something", "BOT|TOM"]], explanation: "Two ATO tiles and two TOM tiles: TOM starts one word and ends another." },
  { id: "wf-e3", title: "Expert board 3", difficulty: "expert", status: "practice", source: null, lanes: [["A thick floor covering", "CAR|PET"], ["An orange root vegetable", "CAR|ROT"], ["A colourful bird that can copy speech", "PAR|ROT"], ["A brass instrument with three valves", "TRUM|PET"]], explanation: "Repeated CAR, ROT and PET tiles; CAR and PAR both fit before ROT, so the clues decide." },
  { id: "wf-e4", title: "Expert board 4", difficulty: "expert", status: "practice", source: null, lanes: [["An insect with broad, colourful wings", "BUT|TER|FLY"], ["A small yellow meadow flower", "BUT|TER|CUP"], ["A cabinet with shelves, often in a kitchen", "CUP|BOARD"], ["The set of keys you type on", "KEY|BOARD"]], explanation: "BUT, TER, CUP and BOARD each appear twice; CUP can end one word or begin another." },
  { id: "wf-e5", title: "Expert board 5", difficulty: "expert", status: "practice", source: null, lanes: [["A pot for brewing a hot drink", "TEA|POT"], ["A small spoon for stirring a cup", "TEA|SPOON"], ["A strong beam of light on a stage", "S|POT|LIGHT"], ["A hole in a road surface", "POT|HOLE"]], explanation: "Three POT tiles, two TEA tiles and a lone S: S+POT could also read SPOT, so the clues decide." },
  { id: "wf-g6", title: "Gentle board 6", difficulty: "gentle", status: "practice", source: null, lanes: [["A hearth in a living room where logs burn","FIRE|PLACE"],["Pale light from the moon at night","MOON|LIGHT"],["Daily printed sheets of reports and photographs","NEWS|PAPER"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-g7", title: "Gentle board 7", difficulty: "gentle", status: "practice", source: null, lanes: [["A place where aircraft take off and land","AIR|PORT"],["A plant that grows in the sea and washes up on beaches","SEA|WEED"],["The wax structure where bees store honey","HONEY|COMB"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-g8", title: "Gentle board 8", difficulty: "gentle", status: "practice", source: null, lanes: [["The strip of hair above your eye","EYE|BROW"],["A small brush for cleaning your teeth","TOOTH|BRUSH"],["The hard covering at the tip of a finger","FINGER|NAIL"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-g9", title: "Gentle board 9", difficulty: "gentle", status: "practice", source: null, lanes: [["A dark panel in a classroom for writing on with chalk","BLACK|BOARD"],["An outdoor area where children play at school","PLAY|GROUND"],["Tasks set by a teacher to be done at home","HOME|WORK"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-g10", title: "Gentle board 10", difficulty: "gentle", status: "practice", source: null, lanes: [["A bag carried on the shoulders","BACK|PACK"],["The area next to the sea where people go on holiday","SEA|SIDE"],["The moment in the morning when the sun first appears","SUN|RISE"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-g11", title: "Gentle board 11", difficulty: "gentle", status: "practice", source: null, lanes: [["A rack for storing books","BOOK|SHELF"],["A rectangle of stiff paper sent from a holiday","POST|CARD"],["A route along which trains run","RAIL|WAY"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-g12", title: "Gentle board 12", difficulty: "gentle", status: "practice", source: null, lanes: [["Natural brightness from the sun during the day","DAY|LIGHT"],["A small orange pet fish kept in a bowl","GOLD|FISH"],["A comfortable seat with supports for your arms","ARM|CHAIR"]], explanation: "Three compounds of two whole words each." },
  { id: "wf-s6", title: "Standard board 6", difficulty: "standard", status: "practice", source: null, lanes: [["A pair of uprights with rungs for climbing","LAD|DER"],["A place where traders sell goods from stalls","MAR|KET"],["A shiny grey-white precious metal","SIL|VER"]], explanation: "Each word splits into two spelling chunks, and the second chunks look interchangeable: only one sharing-out spells all three answers." },
  { id: "wf-s7", title: "Standard board 7", difficulty: "standard", status: "practice", source: null, lanes: [["A person who treats the sick","DOC|TOR"],["A girl or woman with the same parents as you","SIS|TER"],["The coldest season of the year","WIN|TER"]], explanation: "TER is shared by two words, so the clues decide which opening goes with it." },
  { id: "wf-s8", title: "Standard board 8", difficulty: "standard", status: "practice", source: null, lanes: [["A long-eared small mammal kept as a pet","RAB|BIT"],["A short coat","JAC|KET"],["A piece of metal that attracts iron","MAG|NET"]], explanation: "Spelling chunks, not syllables: RAB+BIT, JAC+KET, MAG+NET." },
  { id: "wf-s9", title: "Standard board 9", difficulty: "standard", status: "practice", source: null, lanes: [["A large area thickly covered with trees","FOR|EST"],["The main meal of the evening","DIN|NER"],["A small folding case for banknotes and cards","WAL|LET"]], explanation: "Spelling chunks, not syllables: FOR+EST, DIN+NER, WAL+LET." },
  { id: "wf-s10", title: "Standard board 10", difficulty: "standard", status: "practice", source: null, lanes: [["An eight-legged creature that spins webs","SPI|DER"],["A large wild cat with stripes","TI|GER"],["A small scaly reptile that often basks in the sun","LIZ|ARD"]], explanation: "Spelling chunks, not syllables: SPI+DER, TI+GER, LIZ+ARD." },
  { id: "wf-s11", title: "Standard board 11", difficulty: "standard", status: "practice", source: null, lanes: [["A large fortified building","CAS|TLE"],["A soft cushion for your head in bed","PIL|LOW"],["An underground passage through a hill","TUN|NEL"],["A light open shoe worn in summer","SAN|DAL"]], explanation: "Four lanes with chunks split inside the words: CAS+TLE, PIL+LOW, TUN+NEL, SAN+DAL." },
  { id: "wf-s12", title: "Standard board 12", difficulty: "standard", status: "practice", source: null, lanes: [["A mother or father","PAR|ENT"],["A travelling show with clowns and acrobats","CIR|CUS"],["A round green leafy vegetable","CAB|BAGE"]], explanation: "Spelling chunks, not syllables; CAB+BAGE uses two chunks to spell a two-syllable word." },
  { id: "wf-s13", title: "Standard board 13", difficulty: "standard", status: "practice", source: null, lanes: [["A glass in which you can see yourself","MIR|ROR"],["A glass or plastic container for liquid","BOT|TLE"],["A game of fitting small pieces into a picture","PUZ|ZLE"]], explanation: "Spelling chunks, not syllables: MIR+ROR, BOT+TLE, PUZ+ZLE." },
  { id: "wf-s14", title: "Standard board 14", difficulty: "standard", status: "practice", source: null, lanes: [["A sour yellow citrus fruit","LEM|ON"],["A large sweet fruit with watery flesh","MEL|ON"],["A dish of raw vegetables, often served cold","SAL|AD"]], explanation: "ON appears twice; the clues decide which opening it follows." },
  { id: "wf-e6", title: "Expert board 6", difficulty: "expert", status: "practice", source: null, lanes: [["A fastener sewn on a shirt","BUT|TON"],["A soft white fibre from a plant, used for cloth","COT|TON"],["Meat from a fully grown sheep","MUT|TON"]], explanation: "Three identical TON tiles: any TON can finish any lane, so the challenge is pairing the openings." },
  { id: "wf-e7", title: "Expert board 7", difficulty: "expert", status: "practice", source: null, lanes: [["Any day from Monday to Friday","WEEK|DAY"],["The present day","TO|DAY"],["A period of time away from work or school","HOLI|DAY"],["The day before today","YESTER|DAY"]], explanation: "Four identical DAY tiles: pair each opening with a DAY." },
  { id: "wf-e8", title: "Expert board 8", difficulty: "expert", status: "practice", source: null, lanes: [["A set of steps inside a building, with a rail","STAIR|CASE"],["A flat bag for carrying papers to work","BRIEF|CASE"],["A cover for a pillow","PILLOW|CASE"],["A rectangular bag for carrying clothes when travelling","SUIT|CASE"]], explanation: "Four identical CASE tiles; BRIEFCASE and STAIRCASE are the same length, so the clues decide." },
  { id: "wf-e9", title: "Expert board 9", difficulty: "expert", status: "practice", source: null, lanes: [["A person who delivers letters","POST|MAN"],["A person who delivers bottles to doorsteps in the early morning","MILK|MAN"],["A covered opening in a road leading underground","MAN|HOLE"],["All human beings","MAN|KIND"]], explanation: "Four MAN tiles: MAN ends two words and starts two others." },
  { id: "wf-e10", title: "Expert board 10", difficulty: "expert", status: "practice", source: null, lanes: [["Computers or people linked together","NET|WORK"],["People cooperating to achieve something","TEAM|WORK"],["A painting or sculpture","ART|WORK"],["A basic structure that supports something","FRAME|WORK"]], explanation: "Four identical WORK tiles: pair each opening with a WORK." },
  { id: "wf-e11", title: "Expert board 11", difficulty: "expert", status: "practice", source: null, lanes: [["A game where players shoot a ball through a high hoop","BASKET|BALL"],["A bat-and-ball game with four bases","BASE|BALL"],["The round part of the eye, in its socket","EYE|BALL"],["A game like baseball but with a larger, softer ball","SOFT|BALL"]], explanation: "Four identical BALL tiles: pair each opening with a BALL." },
  { id: "wf-e12", title: "Expert board 12", difficulty: "expert", status: "practice", source: null, lanes: [["A glass building for growing plants","GREEN|HOUSE"],["A building where a court of law meets","COURT|HOUSE"],["A building for storing goods","WARE|HOUSE"],["A luxury flat at the top of a tall building","PENT|HOUSE"]], explanation: "Four identical HOUSE tiles: pair each opening with a HOUSE." },
  { id: "wf-e13", title: "Expert board 13", difficulty: "expert", status: "practice", source: null, lanes: [["A small British coin","PEN|NY"],["Amusing","FUN|NY"],["Bright with sunshine","SUN|NY"]], explanation: "Three identical NY tiles: pair each opening with a NY." },
  { id: "wf-e14", title: "Expert board 14", difficulty: "expert", status: "practice", source: null, lanes: [["The bond between people who like one another","FRIEND|SHIP"],["A vehicle for travelling in outer space","SPACE|SHIP"],["Great difficulty or suffering","HARD|SHIP"],["The position of being in charge of a group","LEADER|SHIP"]], explanation: "Four identical SHIP tiles: pair each opening with a SHIP." },
  { id: "wf-e15", title: "Expert board 15", difficulty: "expert", status: "practice", source: null, lanes: [["A bottom-feeding freshwater fish with whiskers","CAT|FISH"],["A crab, lobster or oyster, say","SHELL|FISH"],["A sea creature with a sword-like snout","SWORD|FISH"],["A floating sea creature with trailing tentacles","JELLY|FISH"]], explanation: "Four identical FISH tiles: any FISH can finish any lane, so the challenge is pairing the openings." },
  { id: "wf-e16", title: "Expert board 16", difficulty: "expert", status: "practice", source: null, lanes: [["A person's native country","HOME|LAND"],["Solid ground, as opposed to an island","MAIN|LAND"],["A person who rents out a house or pub","LAND|LORD"],["A feature that helps travellers find their way","LAND|MARK"]], explanation: "Four identical LAND tiles: LAND ends two words and starts two others." },
  { id: "wf-e17", title: "Expert board 17", difficulty: "expert", status: "practice", source: null, lanes: [["A pale rock used to make cement","LIME|STONE"],["A stage on a journey, or a key event","MILE|STONE"],["A marker over a burial place","GRAVE|STONE"],["A sedimentary rock made of compressed grains","SAND|STONE"]], explanation: "Four identical STONE tiles: any STONE can finish any lane, so the challenge is pairing the openings." },
  { id: "wf-e18", title: "Expert board 18", difficulty: "expert", status: "practice", source: null, lanes: [["A country with its own flag and government","NA|TION"],["Movement from one place to another","MO|TION"],["A creamy liquid rubbed on the skin","LO|TION"],["A magic drink in a fairy tale","PO|TION"]], explanation: "Four identical TION tiles; the first chunks look interchangeable, so the clues decide which opening goes with which lane." },
  { id: "wf-e19", title: "Expert board 19", difficulty: "expert", status: "practice", source: null, lanes: [["Timber washed up by the sea","DRIFT|WOOD"],["Logs cut for burning","FIRE|WOOD"],["An area covered with trees","WOOD|LAND"],["Furniture and fittings made of timber","WOOD|WORK"]], explanation: "Four identical WOOD tiles: WOOD ends two words and starts two others." },
  { id: "wf-e20", title: "Expert board 20", difficulty: "expert", status: "practice", source: null, lanes: [["The slope of a hill","HILL|SIDE"],["The area next to a bed","BED|SIDE"],["A path for pedestrians beside a road","SIDE|WALK"],["A minor event alongside a main attraction","SIDE|SHOW"]], explanation: "Four identical SIDE tiles: SIDE ends two words and starts two others." },
  { id: "wf-m1", title: "Master board 1", difficulty: "master", status: "practice", source: null, lanes: [["Unhealthy, as a district","IN|SA|LUBR|IOUS"],["Healthy, as a climate","SA|LUBR|IOUS"],["Night-time study","LU|CU|BR|ATI|ON"],["Mournful","LU|GU|BRI|OUS"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
  { id: "wf-m2", title: "Master board 2", difficulty: "master", status: "practice", source: null, lanes: [["Beyond all reason or fairness","UNC|ON|SC|ION|AB|LE"],["Linking in a chain","CO|NC|AT|ENAT|ION"],["Deliberate muddying","OB|FU|SC|ATI|ON"],["Sharp scolding","OB|JURG|ATI|ON"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
  { id: "wf-m3", title: "Master board 3", difficulty: "master", status: "practice", source: null, lanes: [["Noisily unruly","OB|ST|RE|PER|OUS"],["Funeral rites","OB|SEQ|UI|ES"],["Perfect example; fifth element","QUI|NT|ES|SE|NCE"],["Fawning, like a flunkey","OB|SEQ|UI|OUS"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
  { id: "wf-m4", title: "Master board 4", difficulty: "master", status: "practice", source: null, lanes: [["Slanted, biased","TEND|EN|TIO|US"],["Pious in a smug way","SANC|TI|MO|NI|OUS"],["Generous in forgiving","MA|GNA|NI|MO|US"],["Done on the quiet","SU|RREP|TI|TIO|US"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
  { id: "wf-m5", title: "Master board 5", difficulty: "master", status: "practice", source: null, lanes: [["Faint-hearted","PU|SIL|LANI|MO|US"],["Cowardice","PUSI|LL|AN|IM|ITY"],["Stingy","PAR|SI|MO|NI|OUS"],["Short of cash","IM|PECU|NI|OUS"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
  { id: "wf-m6", title: "Master board 6", difficulty: "master", status: "practice", source: null, lanes: [["Loud and insistent","VO|CI|FER|OUS"],["Sweetly flowing","MEL|LI|FLU|OUS"],["Insolently abusive","CO|NTU|ME|LIO|US"],["Disdainfully haughty","SU|PER|CI|LIO|US"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
  { id: "wf-m7", title: "Master board 7", difficulty: "master", status: "practice", source: null, lanes: [["Unawareness","OBL|IVI|OU|SNE|SS"],["Bitter in tone","ACR|IM|ONI|OUS"],["Diverse in make-up","HETE|RO|GE|NE|OUS"],["Peevishness","QU|ER|UL|OU|SNE|SS"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
  { id: "wf-m8", title: "Master board 8", difficulty: "master", status: "practice", source: null, lanes: [["Hopelessly old-fashioned","AN|TED|IL|UVI|AN"],["Charitable giving","PH|IL|ANTH|RO|PY"],["People-hater","MIS|ANTH|RO|PI|ST"],["Autumn bloom","CHRY|SAN|TH|EM|UM"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
  { id: "wf-m9", title: "Master board 9", difficulty: "master", status: "practice", source: null, lanes: [["Coin collecting","NUMI|SM|ATI|CS"],["Surrender","CAPI|TU|LA|TI|ON"],["Extreme annoyance","EXAS|PER|AT|ION"],["Torrent of abuse","VI|TU|PER|AT|ION"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
  { id: "wf-m10", title: "Master board 10", difficulty: "master", status: "practice", source: null, lanes: [["Glowing with heat","IN|CAN|DE|SC|ENT"],["Spoiling for a fight","BELL|IG|ER|ENT"],["Unbending in negotiation","IN|TRA|NS|IGE|NT"],["Never before seen","UNP|RE|CE|DE|NT|ED"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
  { id: "wf-m11", title: "Master board 11", difficulty: "master", status: "practice", source: null, lanes: [["Study of law","JUR|IS|PR|UDE|NCE"],["Change of fortune","VI|CI|SS|ITU|DE"],["Habitual silence","TAC|IT|URNI|TY"],["Look of truth","VER|IS|IMIL|ITU|DE"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
  { id: "wf-m12", title: "Master board 12", difficulty: "master", status: "practice", source: null, lanes: [["Formal eulogy","PANE|GYR|IC"],["Brother-killing","FRA|TRIC|ID|AL"],["Free from a tangle","EX|TRIC|ATE"],["Lavish spectacle","EX|TR|AV|AG|ANZA"]], explanation: "Long answers cut into overlapping chunks: several fragments could start or finish more than one word, and only one sharing-out of the whole tray spells every answer." },
];

const membership = loadMembershipSync();
const out = rows.map((r) => {
  const lanes = r.lanes.map(([clue, parts], i) => ({ id: "abcdefgh"[i], clue, length: parts.replace(/\|/g, "").length }));
  const pieces = r.lanes.flatMap(([, parts], i) => parts.split("|").map((text) => ({ lane: lanes[i].id, text })));
  const order = r.keepOrder ? pieces.map((_, i) => i) : createRng(seedFrom(r.id)).shuffle(pieces.map((_, i) => i));
  const idOf = new Map<number, string>();
  order.forEach((pieceIndex, k) => idOf.set(pieceIndex, `t${k + 1}`));
  const tiles = order.map((pieceIndex) => ({ id: idOf.get(pieceIndex)!, text: pieces[pieceIndex].text }));
  const allocation: Record<string, string[]> = {};
  pieces.forEach((pc, i) => (allocation[pc.lane] ??= []).push(idOf.get(i)!));
  const acceptedAnswers = Object.fromEntries(r.lanes.map(([, parts], i) => [lanes[i].id, [parts.replace(/\|/g, "")]]));
  const payload: FragPayload = { lanes, tiles, acceptedAnswers, allocations: [allocation], claimsUnique: false, explanation: r.explanation };
  const textAllocs = acceptedTextAllocations(payload);
  payload.claimsUnique = textAllocs.length === 1;
  const rivals = rivalBoards(payload, membership, 10);
  console.log(r.id, "text allocations", textAllocs.length, "rivals", rivals.length, rivals.slice(0, 4).join("  ;  "));
  return { id: r.id, title: r.title, difficulty: r.difficulty, status: r.status, sourceFixtureId: r.source, payload };
});

writeFileSync(
  join(process.cwd(), "src/games/word-fragments/content/rounds.json"),
  JSON.stringify(
    {
      schemaVersion: 1,
      gameId: "word-fragments",
      rulesVersion: "1.0",
      note: "Demo rounds import the pack fixtures (sourceFixtureId) with their tile ids. Practice rounds are original to this build; tile ids are shuffled so they do not reveal grouping. claimsUnique is set only when the exact allocation solver finds a single sharing-out of fragment texts. Clues are original and not yet human-reviewed.",
      rounds: out,
    },
    null,
    2,
  ) + "\n",
);
